- name: Clean APT cache
  ansible.builtin.apt:
    autoclean: yes
  when: ansible_facts['os_family'] == 'Debian'
    
- name: Remove unusable packages on Debian
  ansible.builtin.apt:
    autoremove: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Clean YUM cache on RedHat
  ansible.builtin.command:
    cmd: yum clean all
  when: ansible_facts['os_family'] == 'RedHat'

- name: Remove unused packages on RedHat
  ansible.builtin.yum:
    autoremove: yes
  when: ansible_facts['os_family'] == 'RedHat'
