- name: Delete specified users
  hosts: all
  become: true

  vars_files:
    - ../vault/vault.yaml
    - ../vars/users.yaml
  
  tasks:
    - name: Delete users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: true  # also home directory
      loop: "{{ users }}"