- name: Upgrade system packages
  hosts: admin

  vars_files:
    - ../vault/vault.yaml
  
  pre_tasks:
    - name: Just ping remote server
      ping:

  tasks:
    - name: Update local repository data
      apt:
        update_cache: yes
      become: true