- name: Upgrade system packages
  hosts: firewall

  vars_files:
    - ../vault/vault.yaml

  pre_tasks:
    - name: Just ping remote server
      ping:

  tasks:
    - name: Update local repository data
      yum:
        update_cache: yes
      become: true